# Generated by Django 6.0.5 on 2026-06-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True, verbose_name='User')),
                ('model_name', models.CharField(max_length=255, verbose_name='Model name')),
                ('instance_id', models.IntegerField(verbose_name='Instance ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('changes', models.JSONField(default=dict, verbose_name='Changes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Store Audit',
                'verbose_name_plural': 'Store Audit',
            },
        ),
    ]
